<?php

class UsersModel1 extends MY_Model
{
    private $tableName='user';
    private $id;
    private $name;
    private $password;
    private $email;
    private $authorised;

    function __construct()
    {
        parent::__construct();
    }

    public function getTableName()
    {
        return $this->tableName;
    }


    /*public function setTableName($tableName)
    {
        $this->tableName = $tableName;
    }*/


    public function getId()
    {
        return $this->id;
    }


   /* public function setId($id)
    {
        $this->id = $id;
    }*/


    public function getName()
    {
        return $this->name;
    }


    public function setName($name)
    {
        $this->name = $name;
    }


    public function getPassword()
    {
        return $this->password;
    }


    public function setPassword($password)
    {
        $this->password = $password;
    }


    public function getEmail()
    {
        return $this->email;
    }


    public function setEmail($email)
    {
        $this->email = $email;
    }


    public function getAuthorised()
    {
        return $this->authorised;
    }


    public function setAuthorised($authorised)
    {
        $this->authorised = $authorised;
    }

    public function addUser($userData)
    {
        //var_dump($userData);die();
        foreach ($userData as $key=>$value)
        {
           $this->setProperty($key,$value);
            var_dump($key,$value);
        }

        $this->save();

    }

    public function getUsers($name = FALSE)
    {
        if ($name === FALSE)
        {
            $query=$this->db->get('user');
            return $query->result_array();
        }

        $query=$this->db->get_where('user',array('name'=>$name));

        return $query->row_array();
    }

    public function save()
    {
        parent::save(); // TODO: Change the autogenerated stub

    }

    public function setProperty($propName, $propValue)
    {
        parent::setProperty($propName, $propValue); // TODO: Change the autogenerated stub
    }


}